### ISSUE TITLE
Behaviour of Docked Scope widget

### ISSUE THREAD

**Issue by rbnpi** [Factoid/sonic-pi#2]
Thought I'd put comments here rather than on Gitter.
I'm running your fork in a virtual Mac under vmware. I find docked scope currently not very useful. When docked either on right or at bottom, the window is not resizable as is for example the help window (which has scroll bars) , so that you can pull it up or down like a blind. At present you can't meaningfully look at other panes when it is open. You can move it by dragging, but can't leave it floating (as is possible with the help window.).

I've added undockingability  by altering

```
scopeWidget->setFeatures(QDockWidget::DockWidgetClosable | QDockWidget::DockWidgetMovable);
```

to

```
scopeWidget->setFeatures(QDockWidget::DockWidgetClosable | QDockWidget::DockWidgetMovable | QDockWidget::DockWidgetFloatable);
```

in main window.cpp which helps.

I've found that you need quite a high window resolution to be able to handle moving the Scope window and/or resizing it effectively. Otherwise I couldn't reduce the vertical size of the Scope window. This could be an issue on lower res screens.

**Comment by Factoid** [comment]
I'm seeing some behaviour on OSX That simply isn't present in Ubuntu, and the whole dock thing seems either totally broken on OSX, or I'm doing it wrong (most likely the latter). Even with your suggestions it's difficult to get the dock to re-dock with sidebars.

**Comment by rbnpi** [comment]
I am getting reasonable behaviour if:
1 screen resolution is quite high 1920x1080 or greater
2 you select full screen mode, first on the app window (top left green button) and then on prefs full screen mode.

If scope window is stuck in size, toggling dark/light mode a couple of times helps.

Another problem is that the menubar background colour does not go dark in dark mode, although the title text does change. May need some tweaking in 
`void MainWindow::updateDarkMode(){`
 although I've not worked out where yet.

Docking has always been quite tricky using for floating windows in Qt on a Mac, but with practice it is not too bad. Not as easy as on Ubuntu. If you double click the Scope window titlebar it will dock.

I think you also should have a line `scopeWidget->setObjectName("scope");` see pref widget setup for comparison.

**Comment by Factoid** [comment]
Pulled in some of these fixes from upstream, and added some size hints which seem to resolve the issue. Least it does on my mac. Submitted PR to upstream, but feel free to checkout my master now to see if this fixes it for you.

**Comment by Factoid** [comment]
Confirmed fixed.
